	DROP DATABASE IF EXISTS cars;
	CREATE DATABASE IF NOT EXISTS cars DEFAULT CHARACTER SET = utf8;
	USE cars; 
	SET character_set_client = utf8;

	/* Start of CARSSYSTEM table */

	CREATE TABLE CARSSYSTEM (
		ID INTEGER NOT NULL AUTO_INCREMENT,
		SYSTEMKEY VARCHAR(40) NOT NULL,
		STRVALUE VARCHAR(40) NOT NULL,
		DESCR VARCHAR(200) NOT NULL,
		PRIMARY KEY(id)
		);

	COMMIT;

	INSERT INTO CARSSYSTEM (SYSTEMKEY, STRVALUE, DESCR) values ("SYSTEMDEPLOY", "cz", "Which country is this system depoloyed.");
	INSERT INTO CARSSYSTEM (SYSTEMKEY, STRVALUE, DESCR) values ("DEFLANG", "en", "Default Display Language.");
	INSERT INTO CARSSYSTEM (SYSTEMKEY, STRVALUE, DESCR) values ("LANG1", "en", "First Display Language.");
	INSERT INTO CARSSYSTEM (SYSTEMKEY, STRVALUE, DESCR) values ("LANG2", "cz", "Second Display Language.");
	INSERT INTO CARSSYSTEM (SYSTEMKEY, STRVALUE, DESCR) values ("LANG3", "de", "Thirst Display Language.");
	INSERT INTO CARSSYSTEM (SYSTEMKEY, STRVALUE, DESCR) values ("LANG4", "ru", "Fourth Display Language.");
	INSERT INTO CARSSYSTEM (SYSTEMKEY, STRVALUE, DESCR) values ("SYSTEM_NOTIFICATION_EMAIL", "notification@carcloud.cz", "Email from address used when sending notifications to users.");
	COMMIT;

	/* End of CARSSYSTEM table */

	/* Start of CTAG table */

	CREATE TABLE CTAG (
	  ID INTEGER NOT NULL AUTO_INCREMENT,			/* Unique Identifier */
	  TAG VARCHAR(50) DEFAULT '' NOT NULL,			/* TAG text */

	  ACTIVE INTEGER DEFAULT '1' NOT NULL,			/* Is item active or not */
	  CDATE TIMESTAMP DEFAULT 0,		/* Create Date */
	  MODDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,				/* Last Update Date */
	  INSUSER VARCHAR(20) DEFAULT 'SYSTEM' NOT NULL,	/* User that inserted this entry */
	  MODUSER VARCHAR(20),					/* User that last modified this entry */

	  PRIMARY KEY(id)
	  );

	COMMIT;

	/* End of CTAG table */
	 
	INSERT INTO CTAG (ID, TAG) VALUES (1, 'YELLOW');
	INSERT INTO CTAG (ID, TAG) VALUES (2, 'YES');
	INSERT INTO CTAG (ID, TAG) VALUES (3, 'SUGAR');
	INSERT INTO CTAG (ID, TAG) VALUES (4, 'SWEET');
	INSERT INTO CTAG (ID, TAG) VALUES (5, 'SPICE');
	INSERT INTO CTAG (ID, TAG) VALUES (6, 'SPICY');
	INSERT INTO CTAG (ID, TAG) VALUES (7, 'SAND');
	INSERT INTO CTAG (ID, TAG) VALUES (8, 'SILVER');
	INSERT INTO CTAG (ID, TAG) VALUES (9, 'SILVERED');
	INSERT INTO CTAG (ID, TAG) VALUES (10, 'SILVERISH');
	INSERT INTO CTAG (ID, TAG) VALUES (11, 'SILVERRED');
	INSERT INTO CTAG (ID, TAG) VALUES (12, 'SILVERYELLOW');
	INSERT INTO CTAG (ID, TAG) VALUES (13, 'SILVERBLACK');
	INSERT INTO CTAG (ID, TAG) VALUES (14, 'SILVERX');

	COMMIT;
